add units
artemovmak/TP_Project_2022 pull request #1
Opened 2022-03-20 17:33 UTC by artemovmak

2022-03-20 17:49 UTC, artemovmak commented
Добавлены паттерн Builder для башень и юнитов. Реализованы диаграммы UML для каждого класса

2022-03-31 18:09 UTC, akhtyamovpavel requested changes
Добрый день!

Мне необходимо описание проекта и план на следующие итерации. Пока что без этого текущую версию принять не могу.

Буду ждать описание и связь между двумя диаграммами (пока что я вижу ее в main)

2022-03-31 18:09 UTC, akhtyamovpavel commented on GamePatterns/TowersPattern/AdvancedTowerBuilder.cpp
> +}
Ставим пропуски строк

2022-03-31 18:09 UTC, akhtyamovpavel commented on GamePatterns/TowersPattern/Building.cpp
> +sf::Vector2i Building::GetPosition() const {
Лучше использовать using для обозначения типа - а то так и будем тянуть sfml

2022-03-31 18:09 UTC, akhtyamovpavel commented on GamePatterns/UnitsPattern/main.cpp
> +  UnitDirector director;
Нужно описание проекта!

Я пока что вижу набор юнитов и зданий - пока что не складывается в основной проект

2022-04-04 07:46 UTC, merged